services:
  repofixer:
    build:
        context: .
        dockerfile: Dockerfile
    #image: kostyamalsev/repofixer:amd #for amd arch
    image: kostyamalsev/repofixer:latest #for arm arch
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - GLOBAL_LLM_SERVICE=AzureOpenAI
      - AZURE_OPENAI_ENDPOINT=https://ai-kostyamalsevai4154623923737068.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-15-preview"
      - AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=gpt-4o
    ports:
     - "8000:8000"
    secrets:
      - AZURE_OPENAI_API_KEY
      - GITHUB_TOKEN_GEN_AI

secrets:
    AZURE_OPENAI_API_KEY:
      file: ./gen-api-key.txt
    GITHUB_TOKEN_GEN_AI:
      file: ./git-api-key.txt